apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: pvc-shared-data
  labels: { app.kubernetes.io/managed-by: Helm }
  annotations:
    "meta.helm.sh/release-name": {{ .Release.Name }}
    "meta.helm.sh/release-namespace": {{ .Release.Namespace }}
spec:
  storageClassName: local-path
  accessModes: [ReadWriteOnce]
  resources:
    requests: { storage: 1Gi }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-colcon-workspace
  labels: { app.kubernetes.io/managed-by: Helm }
  annotations:
    "meta.helm.sh/release-name": {{ .Release.Name }}
    "meta.helm.sh/release-namespace": {{ .Release.Namespace }}
spec:
  storageClassName: local-path
  accessModes: [ReadWriteOnce]
  resources:
    requests: { storage: 5Gi }
