# This example shows the way how to start the VIO in the Docker cotainer
# through Docker compose/lazydocker on a drone. It uses single launchfile
# to launch four nodes:
#   - Bluefox2 camera driver
#   - IMU on a Bluefox2 module by MRS
#   - IMU filter
#   - OpwnVINS VIO

# The launchfile 'vio.launch.py' is launching all the nodes when argument
# 'enable_bluefox_cam_and_imu' is set to true. If it is set to false, only
# VIO node is launched.

# Don't change the volume names without also changing them in up.sh
volumes:

  # Going to be filled with the contents of the
  #       ./shared_data/
  # folder.
  shared_data:

  # Going to be filled with the workspace built by
  #       ../colcon_workspace_builder/
  # folder.
  colcon_workspace:

services:

  # this container primes the shared volumes and allows the content to be place in them
  init:
    image: ctumrs/mrs_uav_system:${MRS_UAV_SYSTEM_VERSION}
    volumes:
      - shared_data:/etc/docker/shared_data:consistent
      - colcon_workspace:/etc/docker/colcon_workspace:consistent

  # zenoh router
  zenoh:
    image: ctumrs/mrs_uav_system:${MRS_UAV_SYSTEM_VERSION}
    network_mode: host
    env_file:
      - ./stack.env
    volumes:
      - /dev:/dev
      - shared_data:/etc/docker/shared_data
    command: bash -c "export ZENOH_ROUTER_CONFIG_URI=`ros2 pkg prefix mrs_uav_deployment`/share/mrs_uav_deployment/config/zenoh/uav_router.json5; ros2 run rmw_zenoh_cpp rmw_zenohd"

  vio:
    image: ctumrs/bluefox2:unstable # should be swapped for stable once the packages are available in it
    network_mode: host
    volumes:
      - /dev/:/dev/
    privileged: true
    env_file:
      - ./stack.env
    entrypoint: [
      "bash", "-c",
      "source /opt/ros/jazzy/setup.sh && ros2 launch mrs_open_vins_core vio.launch.py enable_bluefox_cam_and_imu:=true"
    ]
