volumes:

  config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./config

  logs:
    driver: local
    driver_opts:
      o: bind
      type: logs
      device: ./logs

networks:
  ros:
    driver: bridge

services:

  initialize_logs:
    image: ctumrs/mrs_uav_system:latest
    networks:
      - ros
    env_file:
      - ./variables.env
    volumes:
      - logs:/etc/logs:consistent
    command: bash -c "LOG_FOLDER=$(date +'%Y_%m_%d_%H_%M_%S') && mkdir -p /etc/logs/$$LOG_FOLDER && cd /etc/logs && ln -sfn $$LOG_FOLDER latest"

  ros-master:
    networks:
      - ros
    depends_on:
      - initialize_logs
    image: ctumrs/mrs_uav_system:latest
    env_file:
      - ./variables.env
    volumes:
      - logs:/etc/logs:consistent
    # command: bash -c "roscore | tee /etc/logs/latest/$$HOSTNAME.txt"
    command: bash -c "roscore"

  test:
    depends_on:
      - ros-master
    image: ctumrs/mrs_uav_system:latest
    networks:
      - ros
    volumes:
      - config:/etc/config:consistent
      - logs:/etc/logs:consistent
    env_file:
      - ./variables.env
    # command: bash -c "waitForRos && roslaunch mrs_multirotor_simulator multirotor_simulator.launch custom_config:=/etc/config/mrs_multirotor_simulator.yaml | tee /etc/logs/latest/$$HOSTNAME.txt"
    command: bash -c "waitForRos && roslaunch mrs_multirotor_simulator multirotor_simulator.launch custom_config:=/etc/config/mrs_multirotor_simulator.yaml"
